#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : PyICU
Version  : 2.3.1
Release  : 5
URL      : https://files.pythonhosted.org/packages/e9/35/211ffb949c68e688ade7d40426de030a24eaec4b6c45330eeb9c0285f43a/PyICU-2.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/e9/35/211ffb949c68e688ade7d40426de030a24eaec4b6c45330eeb9c0285f43a/PyICU-2.3.1.tar.gz
Summary  : Python extension wrapping the ICU C++ API
Group    : Development/Tools
License  : MIT
Requires: PyICU-license = %{version}-%{release}
Requires: PyICU-python = %{version}-%{release}
Requires: PyICU-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : importlib_metadata
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pytest
BuildRequires : pytest-python
BuildRequires : wcwidth

%description
## Welcome
        
        Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.
        
        ICU stands for "International Components for Unicode".
        These are the i18n libraries of the Unicode Consortium.
        They implement much of the Unicode Standard,
        many of its companion Unicode Technical Standards,
        and much of Unicode CLDR.

%package license
Summary: license components for the PyICU package.
Group: Default

%description license
license components for the PyICU package.


%package python
Summary: python components for the PyICU package.
Group: Default
Requires: PyICU-python3 = %{version}-%{release}
Provides: pyicu-python

%description python
python components for the PyICU package.


%package python3
Summary: python3 components for the PyICU package.
Group: Default
Requires: python3-core

%description python3
python3 components for the PyICU package.


%prep
%setup -q -n PyICU-2.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1561767569
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/PyICU
cp LICENSE %{buildroot}/usr/share/package-licenses/PyICU/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/PyICU/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
