#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : PyICU
Version  : 2.7.2
Release  : 16
URL      : https://files.pythonhosted.org/packages/17/0f/9d6b7eb01650960239a5d4dc21cd6e7a96921807c043d287bae4b2f440e1/PyICU-2.7.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/17/0f/9d6b7eb01650960239a5d4dc21cd6e7a96921807c043d287bae4b2f440e1/PyICU-2.7.2.tar.gz
Summary  : Python extension wrapping the ICU C++ API
Group    : Development/Tools
License  : MIT
Requires: PyICU-python = %{version}-%{release}
Requires: PyICU-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : importlib_metadata
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pytest
BuildRequires : pytest-python
BuildRequires : six
BuildRequires : six-python
BuildRequires : wcwidth

%description
## Welcome
        
        Welcome to PyICU, a Python extension wrapping the ICU C++ libraries.
        
        ICU stands for "International Components for Unicode".
        These are the i18n libraries of the Unicode Consortium.
        They implement much of the Unicode Standard,
        many of its companion Unicode Technical Standards,
        and much of Unicode CLDR.

%package python
Summary: python components for the PyICU package.
Group: Default
Requires: PyICU-python3 = %{version}-%{release}
Provides: pyicu-python

%description python
python components for the PyICU package.


%package python3
Summary: python3 components for the PyICU package.
Group: Default
Requires: python3-core
Provides: pypi(pyicu)

%description python3
python3 components for the PyICU package.


%prep
%setup -q -n PyICU-2.7.2
cd %{_builddir}/PyICU-2.7.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1618518915
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
